### ISSUE TITLE
Where do you incorporate the material-ui theme?

### ISSUE THREAD

**Issue by nmaves** [takanabe/react-redux-material_ui-boilerplate#10]
I am kinda stuck on that point in my own boilerplate code.

PS I like what you go so far.

**Comment by takanabe** [comment]
@nmaves
 I import material-ui component in each component as follows,
- https://github.com/takanabe/react-redux-material_ui-boilerplate/blob/master/components/MainSection.jsx#L5

**Comment by nmaves** [comment]
Actually I was questioning where you use [material_ui_raw_theme_file.jsx](https://github.com/takanabe/react-redux-material_ui-boilerplate/blob/master/src/material_ui_raw_theme_file.jsx).  I am having trouble in my own code trying to specify a custom theme.

**Comment by takanabe** [comment]
Do you want to find the code that uses [material_ui_raw_theme_file.jsx](https://github.com/takanabe/react-redux-material_ui-boilerplate/blob/master/src/material_ui_raw_theme_file.jsx)? In that case, you should use search box in github and you can find the part.

In this boilerplate [material_ui_raw_theme_file.jsx](https://github.com/takanabe/react-redux-material_ui-boilerplate/blob/master/src/material_ui_raw_theme_file.jsx) is used in [react-redux-material_ui-boilerplate/Header.jsx ](https://github.com/takanabe/react-redux-material_ui-boilerplate/blob/master/components/Header.jsx#L17)
