### ISSUE TITLE
How to update Material-ui and React

### ISSUE THREAD

**Issue by HZSamir** [takanabe/react-redux-material_ui-boilerplate#14]
Hello,
I believe this is the first repo using a package which is not mentioned in the package.json, namely Material-ui. The installed version is 14 and I would like to update to version 15. A "npm i --save material-ui" completely breaks the app.

How should I proceed?

**Comment by lipho** [comment]
@Unforgiven-wanda I have done so here - https://github.com/lipho/react-redux-material_ui-boilerplate

Feel free to let me know if something isn't working.
